<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Applied Data Science - 1&nbsp; Measures of central Tendency</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter_1.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measures of central Tendency</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Applied Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course outline</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter_1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measures of central Tendency</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#arithmetic-mean" id="toc-arithmetic-mean" class="nav-link active" data-scroll-target="#arithmetic-mean"><span class="header-section-number">1.1</span> Arithmetic mean</a>
  <ul class="collapse">
  <li><a href="#some-comments-about-the-arithmetic-mean" id="toc-some-comments-about-the-arithmetic-mean" class="nav-link" data-scroll-target="#some-comments-about-the-arithmetic-mean"><span class="header-section-number">1.1.1</span> Some comments about the arithmetic mean</a></li>
  </ul></li>
  <li><a href="#median" id="toc-median" class="nav-link" data-scroll-target="#median"><span class="header-section-number">1.2</span> Median</a>
  <ul class="collapse">
  <li><a href="#median-some-comments" id="toc-median-some-comments" class="nav-link" data-scroll-target="#median-some-comments"><span class="header-section-number">1.2.1</span> Median: some comments</a></li>
  </ul></li>
  <li><a href="#mode" id="toc-mode" class="nav-link" data-scroll-target="#mode"><span class="header-section-number">1.3</span> Mode</a>
  <ul class="collapse">
  <li><a href="#mode-some-comments" id="toc-mode-some-comments" class="nav-link" data-scroll-target="#mode-some-comments"><span class="header-section-number">1.3.1</span> Mode: some comments</a></li>
  </ul></li>
  <li><a href="#relationship-mean-median-mode" id="toc-relationship-mean-median-mode" class="nav-link" data-scroll-target="#relationship-mean-median-mode"><span class="header-section-number">1.4</span> Relationship: mean, Median, Mode</a></li>
  <li><a href="#measures-of-dispersion" id="toc-measures-of-dispersion" class="nav-link" data-scroll-target="#measures-of-dispersion"><span class="header-section-number">2</span> Measures of dispersion</a>
  <ul class="collapse">
  <li><a href="#range" id="toc-range" class="nav-link" data-scroll-target="#range"><span class="header-section-number">2.1</span> Range</a></li>
  <li><a href="#variance-and-standard-deviation" id="toc-variance-and-standard-deviation" class="nav-link" data-scroll-target="#variance-and-standard-deviation"><span class="header-section-number">2.2</span> Variance and standard deviation</a>
  <ul class="collapse">
  <li><a href="#variance-and-standard-deviation-example" id="toc-variance-and-standard-deviation-example" class="nav-link" data-scroll-target="#variance-and-standard-deviation-example"><span class="header-section-number">2.2.1</span> Variance and standard deviation: Example</a></li>
  <li><a href="#characteristics-of-deviation-measures" id="toc-characteristics-of-deviation-measures" class="nav-link" data-scroll-target="#characteristics-of-deviation-measures"><span class="header-section-number">2.2.2</span> Characteristics of deviation measures</a></li>
  </ul></li>
  <li><a href="#the-coefficient-of-variation" id="toc-the-coefficient-of-variation" class="nav-link" data-scroll-target="#the-coefficient-of-variation"><span class="header-section-number">2.3</span> The coefficient of variation</a></li>
  </ul></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="header-section-number">3</span> Confidence Intervals</a>
  <ul class="collapse">
  <li><a href="#confidence-interval-large-sample" id="toc-confidence-interval-large-sample" class="nav-link" data-scroll-target="#confidence-interval-large-sample"><span class="header-section-number">3.1</span> Confidence interval: large sample</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem"><span class="header-section-number">3.2</span> Central limit theorem</a></li>
  </ul></li>
  <li><a href="#covariance-and-correlation" id="toc-covariance-and-correlation" class="nav-link" data-scroll-target="#covariance-and-correlation"><span class="header-section-number">4</span> Covariance and correlation</a>
  <ul class="collapse">
  <li><a href="#percentiles" id="toc-percentiles" class="nav-link" data-scroll-target="#percentiles"><span class="header-section-number">4.1</span> Percentiles</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Measures of central Tendency</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="arithmetic-mean" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="arithmetic-mean"><span class="header-section-number">1.1</span> Arithmetic mean</h2>
<p>The arithmetic mean, or mean of a set of measurements is defined to be the sum of measurements divided by the total number of measurements.</p>
<p>Usually, the population mean is denoted by <span class="math inline">\(\mu\)</span> and the sample mean is denoted by <span class="math inline">\(\bar{y}\)</span>. The sample mean of a series is defined as,</p>
<p><span class="math display">\[
\bar{y}=\frac{\sum_iY_i}{n}
\]</span></p>
<p>where, <span class="math inline">\(n\)</span> is the number of observations.</p>
<p>Example A sample of <span class="math inline">\(n=15\)</span> overdue accounts in a large department store yields the following amounts due,</p>
<table class="table">
<tbody>
<tr class="odd">
<td>55.2</td>
<td>4.88</td>
<td>271.95</td>
</tr>
<tr class="even">
<td>18.06</td>
<td>180.29</td>
<td>365.29</td>
</tr>
<tr class="odd">
<td>28.16</td>
<td>399.11</td>
<td>807.8</td>
</tr>
<tr class="even">
<td>44.14</td>
<td>97.47</td>
<td>9.98</td>
</tr>
<tr class="odd">
<td>61.61</td>
<td>56.89</td>
<td>82.73</td>
</tr>
</tbody>
</table>
<p>The sample mean is computed as follows,</p>
<p><span class="math display">\[
\bar{y}= \frac{\sum_iY_i}{n}=\frac{55.20+18.06+ .... + 82.73}{15}=\frac{2483.56}{15}=165.57
\]</span></p>
<section id="some-comments-about-the-arithmetic-mean" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="some-comments-about-the-arithmetic-mean"><span class="header-section-number">1.1.1</span> Some comments about the arithmetic mean</h3>
<ul>
<li>It is the most common central tendency measure</li>
<li>There exist only one mean of a dataset/series</li>
<li>The value of the mean is influenced by the extreme values. Trimming or deleting extreme observations helps to reduce/omit that influence</li>
<li>Means of samples from a single population can be combined to get the population mean.</li>
<li>It is applicable to quantitative data only.</li>
</ul>
</section>
</section>
<section id="median" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="median"><span class="header-section-number">1.2</span> Median</h2>
<p>The median of a set of measurements is defined to be the middle value when the measurements are arranged from lowest to highest. So, first we need to sort the dataset from lowest to highest.</p>
<p><span class="math display">\[
y_1 \leq y_2 \leq y_3 \leq .... \leq y_i \leq .. \leq y_n
\]</span></p>
<p>Then, the median of a series will be,</p>
<ul>
<li><span class="math inline">\(\frac{N+1}{2}\)</span>-th observation if <span class="math inline">\(n\)</span> is odd.</li>
<li>Average of <span class="math inline">\(\left(\frac{N}{2}\right)\)</span> and <span class="math inline">\(\left(\frac{N}{2}+1\right)\)</span>-th observation if <span class="math inline">\(n\)</span> is even.</li>
</ul>
<section id="median-some-comments" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="median-some-comments"><span class="header-section-number">1.2.1</span> Median: some comments</h3>
<ul>
<li>It is the central value, 50 percent of the observations lie above it and the rest fall below it.</li>
<li>There is only one median in a dataset</li>
<li>It is not affected by extreme observations</li>
<li>Medians of subsamples cannot be combined to get the median of the population.</li>
<li>It is applicable to quantitative data only</li>
<li>For group data, its value is rather stable even when the data are organized into different categories.</li>
</ul>
</section>
</section>
<section id="mode" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="mode"><span class="header-section-number">1.3</span> Mode</h2>
<p>A mode of a set of measurements is defined to be the measurement that occurs most often, i.e.&nbsp;the highest frequency.</p>
<section id="mode-some-comments" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="mode-some-comments"><span class="header-section-number">1.3.1</span> Mode: some comments</h3>
<p>There can be more than one mode in a dataseries. Modes of the subsamples cann’t be used to determine to formulate the mode of the population It is applicable for both qualitative and quantitative data For grouped data, its value can change depending on the categories used.</p>
</section>
</section>
<section id="relationship-mean-median-mode" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="relationship-mean-median-mode"><span class="header-section-number">1.4</span> Relationship: mean, Median, Mode</h2>
<ul>
<li>When a variable is normally distributed, the mean, median, and mode are the same number.</li>
<li>When the variable is skewed to the left (i.e., negatively skewed), the mean shifts to the left the most, the median shifts to the left the second most, and the mode the least affected by the presence of skew in the data.</li>
<li>When the variable is skewed to the right (i.e., positively skewed), the mean is shifted to the right the most, the median is shifted to the right the second most, and the mode the least affected.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2_1.png" class="img-fluid figure-img"></p>
<figcaption>Relationship among different central tendency measures</figcaption>
</figure>
</div>
</section>
<section id="measures-of-dispersion" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Measures of dispersion</h1>
<section id="range" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="range"><span class="header-section-number">2.1</span> Range</h2>
<p>The range of a set of measurements is defined to be the difference between the largest and the smallest measurements of the set.</p>
<p>From the above dataset we are working on, the smallest values is 4.88 and the largest is 807.80. The range of the data would be,</p>
<p><span class="math display">\[
range = 807.80 - 4.88 = 802.92
\]</span></p>
</section>
<section id="variance-and-standard-deviation" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="variance-and-standard-deviation"><span class="header-section-number">2.2</span> Variance and standard deviation</h2>
<p>The <em>variance</em> of a set of measurements <span class="math inline">\(y_1, y_2, y_3, .... , y_n\)</span>, with a mean of <span class="math inline">\(\bar{y}_n\)</span> is the sum of the squared deviations divided by <span class="math inline">\(n-1\)</span>. Symbolically,</p>
<p><span class="math display">\[
s^2 = \frac{\sum_{i=1}^n(x_i-\bar{x})^2}{n-1}
\]</span></p>
<p>We are assuming, we are working with <strong>samples</strong>. In case of variance we will replace <span class="math inline">\(n-1\)</span> with <span class="math inline">\(n\)</span> in the denominator. Sample variance is denoted by <span class="math inline">\(s^2\)</span> and the population variance is denoted by <span class="math inline">\(\sigma^2\)</span>.</p>
<p>Sample variance is an <em>unbiased estimator</em> of the population variance. That means, if we take different sub-samples from the population, then the average variance of those samples are (roughly) equal to the population variance.</p>
<p>The <strong>standard deviation</strong> is a set of measurements is defined to be the positive square root of the variance. <span class="math display">\[
s = \sqrt{\frac{\sum_{i=1}^n(x_i-\bar{x})^2}{n-1}}
\]</span></p>
<p>As mentioned before, sample standard deviation will be denoted by <span class="math inline">\(s\)</span> and the population standard deviation is denoted by <span class="math inline">\(\sigma\)</span>. In real life, this difference is often ignored.</p>
<section id="variance-and-standard-deviation-example" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="variance-and-standard-deviation-example"><span class="header-section-number">2.2.1</span> Variance and standard deviation: Example</h3>
<table class="table">
<caption>Calories in different Starbucks drinks</caption>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Product</th>
<th>Calories</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dunkin’s Donuts Iced Mocha Swirl latte (whole milk)</td>
<td>240</td>
</tr>
<tr class="even">
<td>Starbucks coffee frappuccino blended coffee</td>
<td>260</td>
</tr>
<tr class="odd">
<td>Dunkin Donuts coffee coolatta</td>
<td>350</td>
</tr>
<tr class="even">
<td>Starbucks Iced Coffee Mocha Espresso (whole Milk and whipped cream</td>
<td>350</td>
</tr>
<tr class="odd">
<td>Starbucks Mocha Flappuccino blended coffee (whipped cream)</td>
<td>420</td>
</tr>
<tr class="even">
<td>Starbucks Chocolate Brownie Flappuccino blended coffee (whipped cream)</td>
<td>510</td>
</tr>
<tr class="odd">
<td>Starbucks Chocolate Flappuccino blended creme (whipped cream</td>
<td>530</td>
</tr>
</tbody>
</table>
<p>To calculate standard deviation and variance first we need to calculate the mean, then the squared differences</p>
<p><span class="math display">\[
\bar{x} = \frac{\sum_{i=1}^nX_i}{n} = \frac{2660}{7} = 380
\]</span></p>
<table class="table">
<thead>
<tr class="header">
<th>Calories</th>
<th><span class="math inline">\((x_i - \bar{x})\)</span></th>
<th><span class="math inline">\((x_i - \bar{x})^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>240</td>
<td>-140</td>
<td>19600</td>
</tr>
<tr class="even">
<td>260</td>
<td>-120</td>
<td>14400</td>
</tr>
<tr class="odd">
<td>350</td>
<td>-30</td>
<td>900</td>
</tr>
<tr class="even">
<td>350</td>
<td>-30</td>
<td>900</td>
</tr>
<tr class="odd">
<td>420</td>
<td>40</td>
<td>1600</td>
</tr>
<tr class="even">
<td>510</td>
<td>130</td>
<td>16900</td>
</tr>
<tr class="odd">
<td>530</td>
<td>150</td>
<td>22500</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>76800</td>
</tr>
</tbody>
</table>
<p>Putting all into the formula, we can get the variance.</p>
<p><span class="math display">\[
s^2 = \frac{\sum_{i=1}^n(x_i-\bar{x})^2}{n-1} = \frac{76800}{6} =  12800
\]</span><br>
And, the standard deviation is,</p>
<p><span class="math display">\[
s = \sqrt{s^2} = \sqrt{12800} = 113.1371
\]</span></p>
</section>
<section id="characteristics-of-deviation-measures" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="characteristics-of-deviation-measures"><span class="header-section-number">2.2.2</span> Characteristics of deviation measures</h3>
<ul>
<li>The greater the spread or dispersion of the data, the larger the range, <span class="math inline">\(\sigma^2\)</span> and <span class="math inline">\(\sigma\)</span>.</li>
<li>The greater the concentration of the data around the central value, the smaller the range, <span class="math inline">\(\sigma^2\)</span> and <span class="math inline">\(\sigma\)</span>.</li>
<li>If the values are all the same (so that there are no variation in the data), the range, <span class="math inline">\(\sigma^2\)</span> and <span class="math inline">\(\sigma\)</span> will all equal to zero.</li>
<li>None of the measures of variation can <em>ever</em> be negative.</li>
</ul>
</section>
</section>
<section id="the-coefficient-of-variation" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="the-coefficient-of-variation"><span class="header-section-number">2.3</span> The coefficient of variation</h2>
<p>Unlike the range, <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(\sigma^2\)</span>, the coefficient of variation is a relative measure expressed as a percentage rather than units of a particular data. The coefficient of variation is equal to the standard deviation by the mean, multiplied by <span class="math inline">\(100\%\)</span>.</p>
<p><span class="math display">\[
CV = \left(\frac{\sigma}{\bar{x}}\right)\times 100\%
\]</span></p>
<p>The coefficient of variation is particularly useful to compare the variability of two different datasets measured in two different units of measurements.</p>
<p>From the previous Starbucks data, the coefficient of variation can be calculated as,</p>
<p><span class="math display">\[
CV = \left(\frac{s}{\bar{x}}\right)\times 100\% = \frac{113.1371}{380} \times 100\% = 28.79\%
\]</span></p>
</section>
</section>
<section id="confidence-intervals" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Confidence Intervals</h1>
<p>The goal here is to estimate the sample information to estimate the population parameter of interest to assess the reliability of the estimate.</p>
<ul>
<li>The unknown population parameter (e.g.&nbsp;mean or proportion) that we are interested in estimating is called <em>target parameter</em>}.</li>
<li>A <em>point estimator</em> of a population is a rule or formula that tells us how to use the sample data to calculate as single number that can be used as an estimate of the target parameter.</li>
<li>An <em>interval estimator or confidence interval</em> is a formula that tells us how to use the sample data to calculate an interval that estimates the target parameter.</li>
</ul>
<section id="confidence-interval-large-sample" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="confidence-interval-large-sample"><span class="header-section-number">3.1</span> Confidence interval: large sample</h2>
<p><strong>CI for a</strong> <span class="math inline">\(\mu\)</span>: Normal <span class="math inline">\(z\)</span>-statistic</p>
<p>Let <span class="math inline">\(x_1, x_2, ... , x_n\)</span> be a random sample of <span class="math inline">\(n\)</span> observations from a normally distributed population with unknown mean <span class="math inline">\(\mu\)</span> and known <span class="math inline">\(\sigma^2\)</span>. Suppose that, we want a <span class="math inline">\(100(1-\alpha)\%\)</span> CI of the population mean. Previously, we saw that,</p>
<p><span class="math display">\[
z = \frac{\bar{x}-\mu}{\sigma/\sqrt{n}}
\]</span></p>
<p>has a <span class="math inline">\(N(0,1)\)</span> distribution and <span class="math inline">\(z_{\alpha/2}\)</span> is the value from the <span class="math inline">\(N(0,1)\)</span> such that the upper tail probability is <span class="math inline">\(\alpha/2\)</span>. We use the basis algebra to find,</p>
<p><span class="math display">\[
1 - \alpha =  \mathbb{P} (-z_{\alpha/2} &lt; z &lt; z_{\alpha/2}) = \mathbb{P} \left(-z_{\alpha/2} &lt; \frac{\bar{x}-\mu}{\sigma/\sqrt{n}} &lt; z_{\alpha/2}\right)
\]</span></p>
<p>which in turn,</p>
<p><span class="math display">\[
\mathbb{P} \left(-z_{\alpha/2} \frac{\sigma}{\sqrt{n}} &lt; \bar{x} - \mu &lt; z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right)
= \mathbb{P} \left(\bar{x}-z_{\alpha/2} \frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \bar{x}+z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right)
\]</span></p>
</section>
<section id="central-limit-theorem" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="central-limit-theorem"><span class="header-section-number">3.2</span> Central limit theorem</h2>
<p>According to the Central Limit Theorem the sampling distribution of the sample mean is approximately normal for large samples. For a <span class="math inline">\(95\%\)</span> confidence level it follows that,</p>
<p><span class="math display">\[
\mathbb{P} \left(\bar{x}-1.96 \frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \bar{x}+1.96\frac{\sigma}{\sqrt{n}}\right)
\]</span></p>
<p>The interval <span class="math inline">\(\bar{x} \pm 1.96\sigma_{\bar{x}}\)</span> is called the large sample <span class="math inline">\(95\%\)</span> confidence interval for the population mean <span class="math inline">\(\mu\)</span>. The term large sample refers to the sample being of sufficiently large size that we can apply the Central Limit Theory and the normal <span class="math inline">\(z\)</span> statistic to determine the form of the sampling distribution of <span class="math inline">\(\bar{x}\)</span>. Empirical research suggests that a sample size <span class="math inline">\(n\)</span> exceeding a value between 20 and 30 will usually yield a sampling distribution of <span class="math inline">\(\bar{x}\)</span>, that is normal.</p>
<p>If the sample means (e.g.&nbsp;<span class="math inline">\(\bar{x}_1, \bar{x}_3\)</span> and <span class="math inline">\(\bar{x}_4\)</span>) falls between the two lines on either side of <span class="math inline">\(\mu\)</span>, then the interval <span class="math inline">\(\bar{x} \pm 1.96\sigma_{\bar{x}}\)</span> will contain <span class="math inline">\(\mu\)</span>; if <span class="math inline">\(\bar{x}\)</span> falls outside the boundaries (e.g.&nbsp;<span class="math inline">\(\bar{x}_2\)</span>), the interval <span class="math inline">\(\bar{x} \pm 1.96\sigma_{\bar{x}}\)</span> will not contain <span class="math inline">\(\mu\)</span>.\ From the Empirical rule, we know that, the area under the normal curve (the sampling distribution of <span class="math inline">\(\bar{x}\)</span> between these boundaries is exactly 0.95. Thus the probability that a randomly selected interval <span class="math inline">\(\bar{x} \pm 1.96\sigma_{\bar{x}}\)</span>, will contain <span class="math inline">\(\mu\)</span> is equal to <span class="math inline">\(0.95\)</span> or <span class="math inline">\(95\%\)</span>.\ Large sample interval estimator requires knowing the value of the population <span class="math inline">\(\sigma\)</span>. In most practical applications, the value of population <span class="math inline">\(\sigma\)</span> is unknown. For large samples, in the absence of <span class="math inline">\(\sigma\)</span>, sample standard deviation <span class="math inline">\(s\)</span> provides a good approximation to <span class="math inline">\(\sigma\)</span>.</p>
</section>
</section>
<section id="covariance-and-correlation" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Covariance and correlation</h1>
<p>Covariance is a measure of the relationship between two random variables. The metric evaluates how much - to what extent - the variables change together. In other words, it is essentially a measure of the variance between two variables. However, the metric does not assess the dependency between variables.</p>
<p><span class="math display">\[
Cov (x, y) = \frac{\sum(x_i - \bar{x})(y_i - \bar{y})}{n}
\]</span></p>
<p>For a sample covariance, we need to deduct 1 from the demoninator, i.e.&nbsp;<span class="math inline">\((n-1)\)</span>.</p>
<ul>
<li>Positive covariance: Indicates that two variables tend to move in the same direction.</li>
<li>Negative covariance: Reveals that two variables tend to move in inverse directions.</li>
</ul>
<p>Using covariance, we can only gauge the direction of the relationship (whether the variables tend to move in tandem or show an inverse relationship). However, it does not indicate the strength of the relationship, nor the dependency between the variables.</p>
<p>Correlation measures the strength of the relationship between variables. Correlation is the scaled measure of covariance. It is dimensionless. In other words, the correlation coefficient is always a pure value and not measured in any units.</p>
<p><span class="math display">\[
\rho = \frac{cov(x, y)}{\sigma_x \sigma_y}
\]</span></p>
<ul>
<li>Correlation value ranges from <span class="math inline">\(-1\)</span> to <span class="math inline">\(+1\)</span>. The correlation of zero indicates zero relationship.</li>
<li><span class="math inline">\(\rho_{x,y} = \rho_{y,x}\)</span></li>
<li>The correlation is not synonimous to causation!</li>
<li>More on this topic will be covered later in the degree program.</li>
</ul>
<section id="percentiles" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="percentiles"><span class="header-section-number">4.1</span> Percentiles</h2>
<p>The <span class="math inline">\(p\)</span>-th percentile of a set of <span class="math inline">\(n\)</span>-measurements arranged in order of magnitude is that value that has at most <span class="math inline">\(p\%\)</span> of the measurements below it and at most <span class="math inline">\((100-p)\%\)</span> above it.</p>
<p>Percentiles are frequently used to describe the results of achievements test scores and the ranking of a person in comparison to the rest of the people taking the examination. Specific percentile of interest are the 25th, 50th and 75th percentiles; often called the lower quantile, the middle quantile (median) and the upper quantile respectively. Similarly, if we divide the data by 10 parts then we refer every part as <em>deciles</em>.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Course outline">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Course outline</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link" aria-label="References">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>